# Generated by Django 5.0.7 on 2024-09-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('A', 'Applicant'), ('C', 'Company'), ('S', 'Staff')], default='A', max_length=1),
        ),
    ]
