version: '3.8'

services:
  django:
    build: ./backend
    command: >
      sh -c " python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              daphne -b 0.0.0.0 -p 8000 app.asgi:application"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env.prod

  # celery:
  #   build: ./backend
  #   command:
  #     sh -c "celery -A app purge -f &&
  #       celery -A app worker --loglevel=info"
  #   volumes:
  #     - ./backend:/usr/src/app
  #   env_file:
  #     - .env.[prod]
  #   restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
