# Generated by Django 5.0.7 on 2024-07-21 13:44

import django.db.models.deletion
import matching.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du secteur')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to=matching.models.get_applicant_resume_path, verbose_name='CV')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Nom de famille')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Ville')),
                ('country', models.CharField(default='', max_length=255, verbose_name='Pays')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Téléphone')),
                ('diploma', models.CharField(default='', max_length=255, verbose_name='Dernier diplôme obtenu')),
                ('target_educational_level', models.CharField(choices=[('Equivalent CAP/BEP', 'Equivalent CAP/BEP'), ('Bac', 'Bac'), ('Bac +2', 'Bac +2'), ('Bac +3', 'Bac +3'), ('Bac +4', 'Bac +4'), ('Bac +5', 'Bac +5'), ('Bac +6 et plus', 'Bac +6 et plus')], default='', max_length=255, verbose_name='Niveau de diplôme visé')),
                ('duration', models.CharField(choices=[('-1', 'Pas de préférence'), ('0', 'Moins de 6 mois'), ('1', '6 mois à 1 an'), ('2', '2 ans'), ('3', '3 ans')], default='-1', max_length=255, verbose_name='Durée du contrat souhaitée')),
                ('contract_type', models.CharField(choices=[("Contrat d'apprentissage", "Contrat d'apprentissage"), ('Contrat de professionnalisation', 'Contrat de professionnalisation')], default='', max_length=255, verbose_name='Type de contrat souhaité')),
                ('location', models.CharField(default='', max_length=255, verbose_name='Lieu désiré pour le travail')),
                ('kilometers_away', models.IntegerField(choices=[(5, 5), (10, 10), (50, 50), (100, 100), (-1, 'Pas de préférence')], default=-1, verbose_name='Distance maximale (km)')),
                ('is_not_signed_in_school', models.BooleanField(default=False, verbose_name="Je n'ai pas encore signé avec une école")),
                ('do_accept_school', models.BooleanField(default=False, verbose_name='Je ne souhaite pas être contacté par les écoles partenaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ManyToManyField(to='matching.sector', verbose_name="Secteur d'activité")),
                ('skills', models.ManyToManyField(to='matching.skill', verbose_name='Compétences')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matching.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Application_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraversion', models.CharField(choices=[('1', 'Pas du tout extraverti'), ('2', 'Plutôt introverti'), ('3', 'Modérément extraverti'), ('4', 'Plutôt extraverti'), ('5', 'Extrêmement extraverti')], max_length=1, verbose_name='Je suis')),
                ('teamwork_preference', models.CharField(choices=[('Indépendamment', 'Travailler seul'), ('En équipe', 'Travailler en équipe')], max_length=100, verbose_name='Ma préférence de travail est')),
                ('reaction_to_change', models.CharField(choices=[('Accueille avec enthousiasme', "Je l'accueille avec enthousiasme"), ('Trouve stressantes', 'Je le trouve stressant')], max_length=100, verbose_name='Face au changement')),
                ('detail_orientation', models.CharField(choices=[('Attentif aux détails', 'Orienté vers les détails'), ("Vision d'ensemble", "Orienté vers la vision d'ensemble")], max_length=100, verbose_name='Je suis plus orienté vers')),
                ('planning_preference', models.CharField(choices=[("Planifier à l'avance", "Planifier à l'avance"), ('Agir de manière spontanée', 'Agir de manière spontanée')], max_length=100, verbose_name='Je préfère')),
                ('work_environment_preference', models.CharField(choices=[('Calme et structuré', 'Un environnement calme et structuré'), ('Dynamique et stimulant', 'Un environnement dynamique et stimulant')], max_length=100, verbose_name='Je préfère travailler dans')),
                ('task_preference', models.CharField(choices=[('Tâches répétitives', 'Des tâches répétitives et bien définies'), ('Tâches variées et créatives', 'Des tâches variées et créatives')], max_length=100, verbose_name='Je préfère des tâches')),
                ('management_preference', models.CharField(choices=[('Supervision étroite', 'Une supervision étroite et un suivi régulier'), ('Autonomie', 'Une autonomie dans la gestion de mes tâches')], max_length=100, verbose_name="En terme d'organisation, je préfère")),
                ('pressure_reaction', models.CharField(choices=[('Mieux sous pression', 'Je travaille mieux sous pression'), ("Besoin d'un environnement moins stressant", "J'ai besoin d'un environnement moins stressant pour bien performer")], max_length=100, verbose_name='En termes de pression :')),
                ('work_motivation', models.CharField(choices=[('Défis et apprentissage', "Les défis et les possibilités d'apprentissage"), ('Stabilité et sécurité', "La stabilité et la sécurité d'emploi")], max_length=100, verbose_name='Ma motivation au travail est')),
                ('interaction_preference', models.CharField(choices=[('Interactions humaines', 'Les interactions avec les autres'), ('Problèmes techniques', 'La résolution de problèmes techniques')], max_length=100, verbose_name="Au sein de l'entreprise, je préfère :")),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matching.application')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name="Nom de l'entreprise")),
                ('adress', models.CharField(default='', max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Ville')),
                ('zip_code', models.CharField(default='', max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=255, verbose_name='Pays')),
                ('description', models.TextField(blank=True, default='', verbose_name="Description de l'activité")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codeAPE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='matching.codeape', verbose_name='Code APE')),
                ('sector', models.ManyToManyField(to='matching.sector', verbose_name="Secteur d'activité")),
            ],
        ),
        migrations.CreateModel(
            name='company_user_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('privilege', models.CharField(default='reader', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('same_entity_location', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=255)),
                ('contract_type', models.CharField(choices=[("Contrat d'apprentissage", "Contrat d'apprentissage"), ('Contrat de professionnalisation', 'Contrat de professionnalisation')], default='Autre', max_length=255)),
                ('target_educational_level', models.CharField(choices=[('Equivalent CAP/BEP', 'Equivalent CAP/BEP'), ('Bac', 'Bac'), ('Bac +2', 'Bac +2'), ('Bac +3', 'Bac +3'), ('Bac +4', 'Bac +4'), ('Bac +5', 'Bac +5'), ('Bac +6 et plus', 'Bac +6 et plus')], default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.company')),
                ('skills', models.ManyToManyField(to='matching.skill')),
            ],
        ),
        migrations.CreateModel(
            name='match_applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('industry_score', models.IntegerField(default=0)),
                ('test_score', models.IntegerField(default=0)),
                ('geographic_score', models.IntegerField(default=0)),
                ('resume_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted_company', 'Accepted_company'), ('Queue_company', 'Queue_company'), ('Canceled_company', 'Canceled_conmapy'), ('Canceled_applicant', 'Canceled_applicant'), ('Fully_accepted', 'Fully_accepted'), ('Finalized_enrollment', 'Finalized_enrollment')], default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.application')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraversion', models.CharField(choices=[('1', 'Pas du tout nécessaire'), ('2', 'Plutôt peu nécessaire'), ('3', 'Modérément nécessaire'), ('4', 'Plutôt nécessaire'), ('5', 'Extrêmement nécessaire')], max_length=1, verbose_name="Niveau d'extraversion requis")),
                ('teamwork_preference', models.CharField(choices=[('Indépendamment', 'Faible importance'), ('En équipe', 'Grande importance')], max_length=100, verbose_name='Importance du travail en équipe')),
                ('reaction_to_change', models.CharField(choices=[('Accueille avec enthousiasme', 'Accueille les changements avec enthousiasme'), ('Trouve stressantes', 'Trouve les changements stressants')], max_length=100, verbose_name='Réaction face au changement')),
                ('detail_orientation', models.CharField(choices=[('Attentif aux détails', 'Attentif aux détails'), ("Vision d'ensemble", "Vision d'ensemble")], max_length=100, verbose_name='Sens du détail')),
                ('planning_preference', models.CharField(choices=[("Planifier à l'avance", "Planification minutieuse à l'avance"), ('Agir de manière spontanée', 'Flexibilité et adaptabilité')], max_length=100, verbose_name='Gestion du temps')),
                ('work_environment_preference', models.CharField(choices=[('Calme et structuré', 'Un environnement calme et structuré'), ('Dynamique et stimulant', 'Un environnement dynamique et stimulant')], max_length=100, verbose_name='Environnement de travail préféré')),
                ('task_preference', models.CharField(choices=[('Tâches répétitives', 'Tâches répétitives et bien définies'), ('Tâches variées et créatives', 'Tâches variées et créatives')], max_length=100, verbose_name='Type de tâches préféré')),
                ('management_preference', models.CharField(choices=[('Supervision étroite', 'Supervision étroite avec suivi régulier'), ('Autonomie', 'Autonomie dans la gestion des tâches')], max_length=100, verbose_name='Style de supervision préféré')),
                ('pressure_reaction', models.CharField(choices=[('Mieux sous pression', 'Travaille mieux sous pression'), ("Besoin d'un environnement moins stressant", "Besoin d'un environnement moins stressant pour bien performer")], max_length=100, verbose_name='Réaction sous pression')),
                ('work_motivation', models.CharField(choices=[('Défis et apprentissage', "Les défis et les possibilités d'apprentissage"), ('Stabilité et sécurité', "La stabilité et la sécurité d'emploi")], max_length=100, verbose_name='Facteurs de motivation')),
                ('interaction_preference', models.CharField(choices=[('Interactions humaines', 'Interactions humaines'), ('Problèmes techniques', 'Résolution de problèmes techniques')], max_length=100, verbose_name="Préférence d'interaction")),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matching.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matching.joboffer')),
            ],
        ),
    ]
