# Generated by Django 5.0.7 on 2024-07-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.applicant')),
            ],
        ),
    ]
