# Generated by Django 5.0.7 on 2024-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_tempapplicant_date_created_alter_tempapplicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempapplicant',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
