# Generated by Django 5.0.7 on 2024-07-26 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_tempapplicant_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.company')),
            ],
        ),
    ]
