# Generated by Django 5.0.7 on 2024-08-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_tempcompany_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la formation')),
                ('level', models.CharField(choices=[('Equivalent CAP/BEP', 'Equivalent CAP/BEP'), ('Bac', 'Bac'), ('Bac +2', 'Bac +2'), ('Bac +3', 'Bac +3'), ('Bac +4', 'Bac +4'), ('Bac +5', 'Bac +5'), ('Bac +6 et plus', 'Bac +6 et plus')], default='', max_length=255)),
            ],
        ),
    ]
