# Generated by Django 5.0.7 on 2024-09-02 15:09

import matching.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, upload_to=matching.models.get_applicant_resume_path, verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='matching.skill', verbose_name='Compétences'),
        ),
    ]
