# Generated by Django 5.0.7 on 2024-09-02 15:58

import matching.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_alter_applicant_resume_alter_applicant_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=matching.models.get_applicant_resume_path, verbose_name='CV'),
        ),
    ]
