# Generated by Django 5.0.7 on 2024-09-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_alter_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.formation'),
        ),
    ]
