# Generated by Django 5.0.7 on 2024-09-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_applicant_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='company',
            name='codeAPE',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='matching.codeape', verbose_name='Code APE'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='France', max_length=255, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.ManyToManyField(blank=True, to='matching.sector', verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Code postal'),
        ),
    ]
