# Generated by Django 5.0.7 on 2024-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_alter_company_codeape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='matching.skill'),
        ),
    ]
