# Generated by Django 5.0.7 on 2024-09-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0017_alter_match_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_applicant',
            name='status',
            field=models.CharField(choices=[(0, 'En attente'), (1, "Accepté par l'entreprise"), (2, "En file d'attente par l'entreprise"), (-1, "Annulé par l'entreprise"), (-2, 'Annulé par le candidat'), (3, 'Entièrement accepté'), (4, 'Inscription finalisée')], default=0, max_length=255),
        ),
    ]
