# Generated by Django 5.0.7 on 2024-10-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0020_joboffer_token_delete_offertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='do_accept_school',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='is_not_signed_in_school',
        ),
    ]
